language: python
python:
  - "3.7.1"
install:
  - pip3 install pytest
  - pip install coverage
script:
  - pytest -s test_unit.py
  - coverage run -m pytest test_unit.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
